# Generated by Django 4.2 on 2024-11-19 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='seller_site',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='trending_score',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
        ),
    ]
