# Generated by Django 4.2 on 2024-11-09 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rename_sku_product_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='click_count',
            field=models.IntegerField(default=0),
        ),
    ]
