# Generated by Django 4.2 on 2024-11-19 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_seller_site_product_trending_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
    ]
