# Generated by Django 4.2 on 2024-11-19 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_product_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='identifier',
        ),
    ]
