# Generated by Django 4.2 on 2024-11-25 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_category_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_difference',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
